# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/Project/Arbitrary Waveform Generator/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/square_rom/square_rom.xci
# IP: The module: 'square_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Project/Arbitrary Waveform Generator/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/square_rom/square_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Xilinx/Project/Arbitrary Waveform Generator/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/square_rom/square_rom.xci
# IP: The module: 'square_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/Project/Arbitrary Waveform Generator/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/square_rom/square_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'square_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
