# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Xilinx/Arbitrary_Waveform_Generator/sin.coe
add_files C:/Xilinx/Arbitrary_Waveform_Generator/square.coe
add_files C:/Xilinx/Arbitrary_Waveform_Generator/Triangle_Wave_Rom.coe
add_files C:/Xilinx/Arbitrary_Waveform_Generator/sawtooth.coe
read_verilog -library xil_defaultlib {
  C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/new/DDS_module.v
  C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/new/contral.v
  C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/new/detect_module.v
  C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/new/rx_bps_module.v
  C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/new/rx_control_module.v
  C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/new/rx_moudle.v
  C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/new/DDS_sun.v
}
read_ip -quiet C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/sin_rom/sin_rom.xci
set_property used_in_implementation false [get_files -all c:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/sin_rom/sin_rom_ooc.xdc]

read_ip -quiet C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/square_rom/square_rom.xci
set_property used_in_implementation false [get_files -all c:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/square_rom/square_rom_ooc.xdc]

read_ip -quiet C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/triangle_rom/triangle_rom.xci
set_property used_in_implementation false [get_files -all c:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/triangle_rom/triangle_rom_ooc.xdc]

read_ip -quiet C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/sawtooth_rom/sawtooth_rom.xci
set_property used_in_implementation false [get_files -all c:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/sources_1/ip/sawtooth_rom/sawtooth_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Arbitrary_Waveform_Generator/Arbitrary_Waveform_Generator.srcs/constrs_1/new/system.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top DDS_sun -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DDS_sun.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DDS_sun_utilization_synth.rpt -pb DDS_sun_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
